spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://seminar4-rds.cpgvbah4f0xo.ap-northeast-1.rds.amazonaws.com:3306/seminar_db?serverTimezone=UTC
    username: admin
    password: seminar4-admin
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
      
auth.jwt:
  issuer: seminar2assignment
  jwtSecret: SEMINAR_SECRET_KEY_MAKE_IT_LONG_ENOUGH
  jwtExpiration: 7200